# Generated by Django 4.1 on 2022-08-30 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beRealClone', '0002_alter_post_latitude_alter_post_longitude_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='createdAt',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='updatedAt',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='createdAt',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='updatedAt',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
