# Generated by Django 4.1 on 2022-10-02 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='bio',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='following',
            field=models.ManyToManyField(related_name='followers', to='account.person'),
        ),
    ]
