# Generated by Django 4.1 on 2022-10-02 19:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_profile_remove_person_following_remove_person_user'),
        ('feed', '0002_remove_post_likes_post_title_alter_post_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='person',
        ),
        migrations.AddField(
            model_name='post',
            name='profile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='account.profile'),
        ),
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.CharField(blank=True, choices=[('Cats', 'https://images.pexels.com/photos/45170/kittens-cat-cat-puppy-rush-45170.jpeg'), ('Elephants', 'https://images.pexels.com/photos/66898/elephant-cub-tsavo-kenya-66898.jpeg'), ('Lion', 'https://images.pexels.com/photos/247502/pexels-photo-247502.jpeg')], max_length=255, null=True),
        ),
    ]
